services:
  - type: web
    name: proyecto_materias
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn proyecto_materias.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-materias-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.13.4